set1=['chutti', 'bhoolna', 'main thak gaya hu', 'mera confidence chala gaya', 'karte', 'bhook nahi lagti', 'dawaai', 'ek hi cheez baar baar', 'karta',
'janam', 'pyar', 'bhram', 'dar','gaya', 'aansu', 'main pareshan hu', 'dosti', 'mujhe khushi nahi milti', 'tut gaya', 'pareshan', 'lmao', 'manzil', 'karne', 'goliyaan',
'ghatna', 'dukhi', 'baat', 'dawai', 'mujhe sukoon nahi milta', 'gussa jaldi', 'kisi ka haath', 'loony',  'udaasi', 'speak nahi',
'mujhe darr lagta hai', 'duniya badal gayi', 'mujhe', 'study nahi ho rahi', 'woh', 'mast nahi', 'kisi se baat', 'dil tut gaya', 'kaam nahi', 'darr lagna', 'dawaiyan',
'darawna', 'main hopeless feel karta hu', 'sochkar', 'udaas', 'main akela hu', 'lagrha', 'bohot bura lag raha',  'jazbaat', 'haath kaatna'
, 'roothi', 'madad', 'koi samajhta nahi', 'thaka hua', 'baad', 'real nahi', 'haa', 'haan','karke', 'dua', 'tootna', 'uljhi soch',
'main overthink kar raha hu', 'toh', 'lagke', 'raha', 'main ghabra raha hu', 'ghar', 'main concentrate nahi kar pa raha', 'mann bhatakta hai'
, 'thartharana', 'bolraha', 'kuch to gadbad', 'routine tutna', 'din bhar kuch nahi khaya', 'main anxiety feel kar raha hu', 'main toot gaya', 'main kya karu'
, 'bojh', 'dukh', 'karma', 'mujhe pata hai','khana', 'udaasiyat','zyaada', 'zyaada sochna', 'sab kuch mess hai', 'rone', 'mansik', 'tu', 'pls', 'aap', 'fikar'
, 'jaldi se', 'pareshaani', 'main tired feel karta hu', 'rha', 'darr', 'dimaag', 'dimag', 'sapne', 'neend nahi', 'mujhe khud samajh nahi', 'mera din kharab hai'
, 'udaasi bhara',  'ujala','seene mein dard', 'cheez', 'understanding nahi', 'huh', 'tab', 'bolrahi', 'main kuch kar nahi pa raha'
, 'bura hoga', 'maa', 'jab', 'theek nahi','theek','hun', 'main thoda better feel kar raha hu', 'bejaan', 'routine change', 'mera jeene ka mann nahi'
, 'low feel ho raha', 'chillana', 'disorganized', 'zindagi khatam', 'hui', 'soch soch ke thak gaya', 'main udaas rehta hu', 'vibe nahi aa rahi'
, 'bheed se dar', 'andherapan', 'cheezein bhoolna', 'mera future dark hai', 'apka', 'par', 'lagraha', 'main dukhi hu', 'hmm', 'mai', 'phir'
, 'khaali', 'tha', 'mera', 'vichar', 'goli', 'paranoia', 'ho', 'ma', 'pareshaan', 'pagal', 'unki', 'bed se utha nahi jaa raha', 'main gussa ho jata hu', 'pareshani'
, 'kaam adhura chhodna', 'bohot tez bolna', 'mera mann udaas hai', 'woh din yaad aata hai', 'doubt', 'shakl badalna', 'ekdum se sad', 'sab bore lagta hai', 'thaka dimag'
, 'zehni', 'wo', 'khana nahi khaya', 'jeena nahi', 'chhota sound bhi', 'karraha', 'vo', 'focus nahi', 'dimaagi beemari', 'voices sunai de rahi', 'chup nahi baithna'
, 'mohabbat', 'ya', 'ekdum se gussa', 'chain', 'thak chuka', 'haath kaapna', 'udaasi mein', 'zehniyat', 'jee nahi lagta', 'bhot stress hai', 'alag duniya'
, 'mansik swasthya', 'mujhe chain nahi mil raha', 'mere', 'mujhe kuch acha nahi lagta', 'kuch bhi karne ka mann nahi', 'hai', 'bohot zyada khush'
, 'surakshit nahi', 'bohot thakan hai', 'sab khatam lagta', 'dar jaana', 'magar', 'bohot stress hai', 'gussa control nahi', 'umeed', 'mujhe dard ho raha hai'
, 'kaun', 'uljhan', 'life khatam lagti hai', 'khush', 'mental hai', 'uski', 'bechaini', 'main confident nahi hu', 'bohot pressure hai', 'tere', 'mujhe kuch dikhai nahi de raha'
, 'bhot pressure hai', 'repeat karna', 'dil toot gaya', 'mujhse', 'sirf', 'dil udaas hai', 'papa', 'muskuraahat', 'jhagda', 'rahe', 'flashbacks aa rahe', 'mujhe bas sona hai'
, 'dostana', 'mujhe rona aa raha hai', 'tension ho rahi hai', 'change pasand nahi', 'help chahiye', 'bohot fast', 'bas sochta rehta', 'hona'
, 'nirash', 'main', 'kuch acha nahi lagta', 'achha', 'energy zyada', 'meri', 'acha', 'thoda', 'ruk gaya hu', 'rhi', 'kyun', 'kyunki', 'sach nahi lagta', 'ek jagah nahi rukta'
, 'nahi', 'kaaran', 'loud sound', 'zyada soch liya','liya', 'sir dard', 'thi', 'bhatakna', 'main kabhi khush nahi', 'kaatna', 'mujhe akela chhod do', 'raat ko darr'
, 'mujhe ghabrahat ho rahi hai', 'dard', 'energy nahi', 'ghabrahat', 'marna', 'bolke', 'mood badalna', 'bojhila', 'koi dekh raha hai', 'saans lene', 'dost'
, 'aankhon mein dekhna nahi', 'hogi', 'socializing', 'hehe', 'hoga', 'mera focus nahi lagta', 'apne', 'dil', 'bhagwan', 'kam neend', 'log mere peeche', 'shanti', 'huna'
, 'daraawne sapne', 'mujhe madad chahiye','shaq', 'izzat', 'firbhi', 'dhyaan nahi', 'galat lagta', 'feelings samajh', 'sochraha', 'karna'
, 'mera mood kharab hai', 'mann nahi', 'uska', 'raat bhar soya nahi', 'main fail ho gaya', 'teri', 'rona', 'akelapan', 'ulta seedha sochna'
, 'samajhna mann nahi lag raha','muskaan', 'kyu', 'feelkarraha', 'mar jaana', 'bhavna', 'adhoora', 'mujhe neend nahi aati', 'kar', 'dimag ki beemari'
, 'hogaya', 'marna mood off', 'awaazein sunna', 'log baatein kar rahe', 'main irritate ho jata hu', 'jazbaati', 'apni', 'tum', 'main zyada sochta hu'
, 'pasina', 'mera control nahi hai', 'dil nahi lagta', 'haath', 'soch', 'mann', 'raat ko sona nahi', 'udaasiyaan', 'sleep nahi aati', 'trigger', 'samajh nahi aata'
, 'gham', 'sahi nahi', 'hu', 'rishta', 'andar','baatein', 'koi', 'nirasha', 'dimag kharab', 'thand', 'bhavnaayein', 'karna kya hai samajh nahi', 'khauf'
, 'fir', 'parivaar', 'baat nahi karta', 'mein', 'na', 'rishte', 'soch-vichar', 'bhool jaana', 'thakaan', 'sabse alag feel karta', 'chinta', 'bura lag raha', 'sab bekaar lagta'
, 'karrha', 'tension le li', 'behen', 'roothna', 'dekhkar', 'tanha', 'uljha', 'main pagal ho jaunga', 'zindagi se thak gaya', 'main disturb hu', 'mann nahi lag raha'
, 'kaam', 'uthne ka mann nahi', 'overthink kar raha', 'jalan', 'bilkul', 'padhai', 'mera dimaag kharab hai', 'tanhaai', 'khushi', 'dimaag kharab', 'arre', 'pehle', 'kuch heavy lag raha'
, 'shivering', 'yaar', 'sukh', 'sochna', 'main tension me hu', 'pyaar', 'ekdum sad', 'dimagi', 'hamesha late', 'karriha', 'bhool'
, 'system hang', 'kismet', 'usse', 'thaka', 'kuch', 'kharcha zyada', 'kiya', 'duniya', 'akela khelna', 'kitna', 'dost nahi', 'main kuch mehsoos nahi kar raha'
, 'bhi', 'main khush nahi hu', 'mujhe kuch samajh nahi aata', 'sab kuch khatam ho gaya', 'hua', 'saans ruk rahi', 'mujhe samajh nahi aa raha', 'tera', 'kaam mein mann nahi'
, 'humesha darr', 'dar lag raha hai',  'bas rona aa raha', 'lagta hai sab khatam ho gaya', 'bhai', 'naseeb','sunn', 'zyada', 'sunn ho jaana', 'andhera'
, 'gussa', 'likhkar', 'sab kuch bekaar lagta hai', 'bechain', 'meri zindagi barbaad hai', 'maarne ka mann', 'scene kharab', 'kisi se baat nahi karni'
, 'touch karna','soch raha hu', 'khush nahi', 'samajh', 'kuch bhi karne ka mann nahi mandir', 'niraasha', 'hadsa', 'dukhdai', 'hoon'
, 'noise se problem', 'pet dard', 'akalepan', 'mera mood off hai', 'bojhal', 'sannaata', 'main chala', 'mera mann khali hai', 'sukoon', 'akela'
, 'ajeeeb lagta', 'abhi', 'unka', 'paagal', 'ky', 'kartai', 'kisi ko fark nahi', 'humeesha', 'main recover kar raha hu', 'dhyaan nahi lag raha', 'alag rehna', 'chhod diya', 'mujhko'
,'hamesha', 'honi', 'gujra', 'mota', 'log,', 'bacho', 'hojayegi', 'ane', 'chala', 'pr', 'deta', 'krna', 'lagatar', 'kaafi', 'seekh','lenge', 'milta', 'himmat', 'sora'
, 'le', 'matlab', 'iskliye', 'hone', 'chla', 'lagega', 'saans', 'chahte', 'jitna', 'bhagne', 'davai', 'magajmari', 'paise', 'pao', 'sb', 'kala', 'yeah', 'thakan', 'padna'
, 'sali', 'lekar', 'kare', 'ka', 'tanab', 'mahine', 'beti', 'rhta', 'bahar', 'bete', 'chodo', 'bahan', 'musalmanon', 'ta', 'tak', 'peheli', 'kahan'
, 'mummy', 'sakta', 'hain', 'rehna', 'saath', 'khud', 'aisa', 'ne', 'apko', 'alag', 'tareeka', 'yaha', 'lgta', 'jayda'
, 'muzse', 'lagte', 'bass', 'kahe', 'paoogi', 'ko', 'ati', 'uss', 'murthy', 'bht', 'patni', 'jarur', 'apke', 'aapke', 'biwi', 'thaa', 'humesha'
, 'gye', 'es', 'bol', 'inti', 'neend', 'aapki', 'hizre', 'sa', 'ata', 'dam', 'suno', 'mat', 'kuc', 'hee', 'aaya', 'hum', 'ab', 'bhalu'
, 'sochne', 'chuka', 'agr', 'bhaiya',  'wjah', 'lagta', 'nikali', 'bolte', 'kam', 'loge', 'ladka', 'rehti', 'thik', 'kuchh', 'chukane'
, 'bahut', 'leke', 'kyuki', 'kaise', 'jaisa', 'skoon', 'ladki', 'krne', 'bethi', 'musk', 'sath', 'pdaayi', 'rahiye',  'phele', 'bachpan', 'guzar', 'karoge'
, 'paanch', 'lo', 'padta', 'aise', 'ilawa', 'jisse', 'jiske', 'hojayega', 'jata', 'utha', 'pata', 'krti', 'aisi', 'aa', 'hamara', 'zada', 'narayan'
, 'streffie', 'paisa', 'farak', 'uper', 'lga', 'ldayi', 'wala', 'itna', 'sahi', 'din', 'baar', 'karo', 'lok', 'saare', 'ke', 'ki', 'baari', 'kis'
, 'liye', 'apna', 'chiz', 'raheta', 'hoti','sakte', 'ja', 'krke', 'jiyada', 'jisme', 'kabhi', 'jyada', 'lagti', 'ha', 'chlane', 'utna', 'hissab', 'kai', 'mile'
, 'skte', 'mana', 'bdde', 'baki', 'bole', 'isliye', 'kali', 'bataye', 'kab', 'jaya', 'humare', 'gadi', 'kya', 'adhuri', 'aapko', 'iski', 'lekin', 'nnlogo', 'bua'
, 'sab', 'huyi', 'peet', 'tumhare', 'pta','shuru', 'taraha', 'vi', 'krta', 'aane', 'chalta', 'deti', 'haro', 'pe', 'upar', 'gov', 'hath'
, 'nikal', 'yaad', 'leker', 'galti', 'lere', 'yrr', 'yeh', 'akeli', 'chahe', 'se', 'bhukh', 'baaki', 'udasi', 'cure', 'bas', 'zarurat', 'udhar', 'kr', 'lage'
, 'samay', 'acche', 'dal', 'li', 'chahiye', 'aya', 'aour', 'desh', 'itni', 'badi', 'jao', 'hota', 'ek', 'isse', 'jane', 'bura'
, 'huya', 'sakun', 'aage', 'shayed', 'nind', 'dene', 'pura', 'directors', 'jakar', 'fyda', 'jayega',  'pohoch', 'de', 'hisaab', 'thodi'
, 'kisi', 'logon', 'roj', 'yea', 'sabhi', 'unhe', 'nhi', 'isme', 'chuki', 'gais', 'ni', 'lete', 'pehechan', 'dekh', 'bta', 'sabse', 'aur'
, 'jindgi', 'gori', 'jitana', 'bhut', 'lakin', 'ghnte', 'kahi', 'bada', 'lagg', 'bata', 'hawa', 'agar', 'chalu', 'milli', 'elon', 'leta'
, 'ye', 'hisab', 'phle', 'bddi', 'dono', 'lena', 'ayega', 'per', 'saal', 'hote', 'doosri', 'kano', 'jaise', 'bana', 'insaan', 'maine', 'je', 'jaldi'
, 'jaata', 'hoon,', 'inka', 'jo', 'bar', 'ghut', 'aati', 'jiss', 'bohot', 'degi', 'karega', 'yahi', 'aaj', 'moti', 'koyi', 'tarakki', 'sakti', 'behan', 'har', 'jaye'
]
